name: books_store_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.3.1
  flutter_progress_hud: ^2.0.0
  fluttertoast: ^8.0.9
  flutter_svg: ^1.0.3
#  flutter_svg: ^0.22.0
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  http: ^0.13.4
  fl_chart: ^0.45.1
  searchfield: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
